module.exports = {
  schemaSidebar: [
    {
      type: "category",
      label: "API reference",
      collapsible: false,
      collapsed: false,
      items: [{ type: "doc", id: "index" }],
    },

    {
      type: "category",
      label: "Top level API",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Queries",
          items: [
            {
              type: "autogenerated",
              dirName: "queries",
            },
          ],
        },
        {
          type: "category",
          label: "Mutations",
          items: [
            {
              type: "autogenerated",
              dirName: "mutations",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Types",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Objects",
          items: [
            {
              type: "autogenerated",
              dirName: "objects",
            },
          ],
        },
        {
          type: "category",
          label: "Inputs",
          items: [
            {
              type: "autogenerated",
              dirName: "inputs",
            },
          ],
        },
        {
          type: "category",
          label: "Enums",
          items: [
            {
              type: "autogenerated",
              dirName: "enums",
            },
          ],
        },
        {
          type: "category",
          label: "Unions",
          items: [
            {
              type: "autogenerated",
              dirName: "unions",
            },
          ],
        },
        {
          type: "category",
          label: "Interfaces",
          items: [
            {
              type: "autogenerated",
              dirName: "interfaces",
            },
          ],
        },
        {
          type: "category",
          label: "Scalars",
          items: [
            {
              type: "autogenerated",
              dirName: "scalars",
            },
          ],
        },
        {
          type: "category",
          label: "Directives",
          items: [
            {
              type: "autogenerated",
              dirName: "directives",
            },
          ],
        },
      ],
    },
  ],
};
