name: Docs

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install
        run: yarn

      - name: Download schemas
        run: yarn graphql-update-schemas

      - name: Rebuild API reference
        run: yarn api-reference

      - name: Build
        run: yarn build

      - name: Deploy
        if: "contains('refs/heads/main', github.ref)"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
